name: CI

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-${{ matrix.node }}-

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm t
